#!/bin/bash

nasm -f elf32 loader.s
nasm -f elf32 io.s


i386-elf-gcc -ffreestanding -Wall -Wextra -Werror -c io.c -o ioc.o
i386-elf-gcc -ffreestanding -Wall -Wextra -Werror -c kernel.c -o kernel.o

i386-elf-ld -T linker.ld -melf_i386 loader.o io.o kernel.o ioc.o -o kernel.elf 

cp kernel.elf iso/boot

genisoimage -R                              \
                -b boot/grub/stage2_eltorito    \
                -no-emul-boot                   \
                -boot-load-size 4               \
                -A os                           \
                -input-charset utf8             \
                -quiet                          \
                -boot-info-table                \
                -o os.iso                       \
                iso


