#!/bin/bash

git add gdt.c gdt_loader.s giten idt.c idt_loader.s include/gdt.h include/idt.h include/io.h include/memory.h io.c io.s kernel.c linker.ld loader.s memory.c README.md

git commit -m "$1"

git push -u origin master
